# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Peter Leschev'
tagline:             Blog
description:         "Peter Leschev's Blog"
url:                 http://peter.leschev.com
paginate:            5
